const stores=['Falabella','Ripley','Oechsle','Plaza Vea','Promart','Sodimac','Hiraoka','Coolbox','Mercado Libre','Linio','Real Plaza','Inkafarma','Mifarma','La Curacao','Efe','HP Store'];
const categories=['Todas','Tecnología','Mascotas','Deporte y Aire Libre','Belleza y salud','Electrohogar','Moda','Hogar'];
const products=[{brand:'PHILIPS',name:"Televisor Philips Google TV 58'' LED 4K",category:'Tecnología',prices:{Falabella:1299,Ripley:1399,Oechsle:1499,'Plaza Vea':1549}},{brand:'SAMSUNG',name:'Lavaseca Samsung Ecobubble 20kg/12kg Gris',category:'Electrohogar',prices:{Falabella:2999,Ripley:3199,Oechsle:3399,'La Curacao':3599}},{brand:'ASUS',name:"Laptop ASUS ExpertBook 15.6'' Intel Core i5 512GB",category:'Tecnología',prices:{Hiraoka:2219,Coolbox:2399,Falabella:2499,'Mercado Libre':2349}},{brand:'BOSCH',name:'Aspiradora Bosch Serie 4 2L alta potencia',category:'Electrohogar',prices:{Promart:899,Sodimac:979,Falabella:1099}},{brand:'EPSON',name:'Impresora multifuncional Epson L3350 WiFi',category:'Tecnología',prices:{Hiraoka:699,'HP Store':759,Ripley:799,'Mercado Libre':729}},{brand:'ADIDAS',name:'Zapatillas de training hombre Rapidmove',category:'Moda',prices:{Falabella:300,Ripley:349,'Mercado Libre':329}}];
let active='Todas';
const money=n=>`S/${n.toLocaleString('es-PE')}`;
function renderStores(){document.querySelector('#stores').innerHTML=stores.map(s=>`<span>${s}</span>`).join('');document.querySelector('#store-count').textContent=`${stores.length}+`;}
function renderFilters(){document.querySelector('#filters').innerHTML=categories.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{active=b.dataset.cat;render();});}
function render(){const q=document.querySelector('#search').value.toLowerCase();const filtered=products.filter(p=>(active==='Todas'||p.category===active)&&`${p.brand} ${p.name}`.toLowerCase().includes(q));document.querySelector('#saving-total').textContent=money(filtered.reduce((s,p)=>{const v=Object.values(p.prices);return s+Math.max(...v)-Math.min(...v)},0));document.querySelector('#grid').innerHTML=filtered.map(p=>{const entries=Object.entries(p.prices).sort((a,b)=>a[1]-b[1]);const best=entries[0],high=entries.at(-1);const pct=Math.round((high[1]-best[1])*100/high[1]);return `<article class="card"><button class="fav">♡</button><div class="image">🛒</div><small>${p.brand}</small><h3>${p.name}</h3><p class="price">${money(best[1])}</p><p class="save">↘ ${pct}% de ahorro en ${best[0]}</p><details><summary>Ver precios en ${entries.length} tiendas</summary>${entries.map(([store,price])=>`<div class="row"><span>${store}</span><b>${money(price)}</b></div>`).join('')}</details><button class="buy">Comprar en tienda</button></article>`}).join('')||'<p class="empty">No encontramos productos con esos filtros.</p>';renderFilters();}
document.querySelector('#search').addEventListener('input',render);renderStores();render();
